### ISSUE TITLE
observed prevalence is always zero

### ISSUE THREAD

**Issue by rmnldwg** [rmnldwg/lyscripts#70]
The `num_match` that is stored in the metadata of the HDF5 file produced by the `lyscripts compute prevalence` command is always zero. However, it should reflect the number of patients that we observed with the given diagnosis.

**Comment by rmnldwg** [comment]
This issue only occurs when the scenario is defined like this:

```yaml
scenarios:
  - t_stages: [early]
    diagnosis:
      ipsi:
        CT: {II: "healthy"}
```

instead of

```yaml
scenarios:
  - t_stages: [early]
    diagnosis:
      ipsi:
        CT: {II: true}
```

This is because in the former case, [`lyscripts`] creates a `C` object from [`lyDATA`] like this:

```python
C("CT", "ipsi", "II") == "healthy"
```

When querying the data, this evaluates to `False` for all patients, because those columns contain `True`, `False`, or `None`, never `"healthy"`.

[`lyscripts`]: https://lyscripts.readthedocs.io
[`lydata`]: https://lydata.readthedocs.io
